services:
  backend:
    build:
      context: ./quizmaster-project/backend
      dockerfile: Dockerfile
    container_name: quizmaster-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quizmaster-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
